services:
  mariadb:
    image: 'mariadb:latest' 
    environment:
      - 'MARIADB_DATABASE=db-users'
      - 'MARIADB_PASSWORD=abdelilah'
      - 'MARIADB_ROOT_PASSWORD='
      - 'MARIADB_USER='
    ports:
      - '3306:3306'
    volumes:
      - '/home/abdelilah/mariadb_data:/var/lib/mysql'
